version: 0.2

phases:
  install:
    commands:
      - echo Install started on `date`
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Post_build started on `date`

artifacts:
  files:
    - target/messageUtil-1.0.jar