version: 0.2

env:
  variables:
    REGION: "my-region"

phases:
  install:
    commands:
      - echo Install started on `date`
      - echo $AWS_REGION
      - echo $AWS_DEFAULT_REGION
      # - apt update
      # - apt install jq
  build:
    commands:
      - echo Build started on `date`
      # - echo `pwd`
      # - ls -lat recipes
      - ls -lat recipes/com.annakie.Publisher-1.0.0-cloud.json
      - aws greengrassv2 create-component-version --inline-recipe fileb://recipes/com.annakie.Publisher-1.0.0-cloud.json --region $AWS_REGION
  post_build:
    commands:
      - echo Post_build started on `date`

# artifacts:
#   files:
#     - target/messageUtil-1.0.jar
# 