version: 0.2

phases:
  install:
    commands:
      - echo Install started on `date`
      # - apt update
      # - apt install jq
  build:
    commands:
      - echo Build started on `date`
      # - echo `pwd`
      # - ls -lat
      - aws greengrassv2 create-component-version --inline-recipe fileb://artifacts/com.annakie.Publisher-1.0.0-cloud.json --region us-east-1
  post_build:
    commands:
      - echo Post_build started on `date`

# artifacts:
#   files:
#     - target/messageUtil-1.0.jar